### ISSUE TITLE
Unpacking doesn't keep file permissions

### ISSUE THREAD

**Issue by lioramilbaum** [poise/poise-archive#1]

**Comment by coderanger** [comment]
Can you be more specific? Which provider would be a good starting point.

**Comment by lioramilbaum** [comment]
I have a zip file which contains among other file types, shell scripts.  Running an unzip command preserves their execute permission. Executing poise_archive doesn't.
How do I figure which provider is used? I am new to Chef.

**Comment by coderanger** [comment]
Zip files are always handled by RubyZip, and that API I am calling does check file permissions inside RubyZip (except setuid and setgid bits for safety). Are you 100% sure the mode bits in the zipfile itself are correct?

**Comment by coderanger** [comment]
Relevant code here: https://github.com/poise/poise-archive/blob/master/lib/poise_archive/archive_providers/zip.rb#L58

and in RubyZip: https://github.com/rubyzip/rubyzip/blob/master/lib/zip/entry.rb#L384-L392

**Comment by lioramilbaum** [comment]
I have looked at the code. It looks like file permissions are taken care of. But, it doesn't for my zip file. I can send you the zip file to reproduce the problem.

**Comment by coderanger** [comment]
If you could attach the file to this ticket that would be perfect :)

**Comment by lioramilbaum** [comment]
https://s3-eu-west-1.amazonaws.com/lmbgalaxy/IBM/UCD/ibm-ucd-6.2.1.2.801550.zip

**Comment by coderanger** [comment]
Can you give me an example of a script that is being unpacked incorrectly (or is it all of them)?

**Comment by coderanger** [comment]
Never mind, it's all of them.

**Comment by coderanger** [comment]
Fix was released in 1.2.1.

**Comment by lioramilbaum** [comment]
Got it. Worked perfectly.
