### ISSUE TITLE
The zip content doesn't appear

### ISSUE THREAD

**Issue by Lechucico** [poise/poise-archive#12]
This is the code:

```
poise_archive 'https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip' do
  destination '/usr/local/bin'
end
```

Nothing appears on /usr/local/bin

**Comment by coderanger** [comment]
Yep, Hashicorp archives don't match the normal FOSS standard of having a top-level folder so `strip_components 0` is needed until such time as I make it automatic.
