### ISSUE TITLE
Deprecated features used!

### ISSUE THREAD

**Issue by lioramilbaum** [poise/poise-archive#2]
Deprecated features used!
   chef_gem[rubyzip] chef_gem compile_time installation is deprecated at 1 location:
     - /var/chef/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:47:in `install_rubyzip'
   chef_gem[rubyzip] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
     - /var/chef/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:47:in `install_rubyzip'
   chef_gem[rubyzip] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
     - /var/chef/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/zip.rb:47:in `install_rubyzip'

**Comment by coderanger** [comment]
It's fine, that warning has a long and complicated history.
