### ISSUE TITLE
Already downloaded file in kitchen cache will stop archive from extracting when using kitchen-dokken

### ISSUE THREAD

**Issue by tanner-bruce** [poise/poise-archive#9]
Not sure if this belongs more in kitchen-dokken or here, sorry.

Kitchen-dokken bind mounts /opt/kitchen which has the side effect of preserving /opt/kitchen/cache across runs even after running `kitchen destroy`.

When the previously downloaded archive is found in the cache, poise-archive considers everything up to date and does not extract the archive, even though there are no files in the destination.

**Comment by coderanger** [comment]
That's going to interfere with anything using cached remote files so it probably needs to be solved in dokken too, but it is a known issue with this and is the main reason it hasn't been moved into Chef core.
